window:
  theme: com.kokakiwi.mclauncher.ui.simple.SimpleTheme                                          # Theme du launcher, si non indique, il utilise SimpleTheme
login:
  offlineMode: false
launcher:
  gameHost: 'www.minecraft.net'